import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * search_form.java
 *
 * Created on Nov 26, 2018, 11:53:38 AM
 */

/**
 *
 * @author ASUS
 */
public class search_form extends javax.swing.JFrame {
Connection con;
            ResultSet rs;
            Statement smt;
            PreparedStatement pst;
    /** Creates new form search_form */
    public search_form() {
  
initComponents();
        fill();
    }
    public void fill()
    {
         try
         {

            String uid="root";
            String pwd="";
            String url="jdbc:mysql://localhost:3306/project";
            con=DriverManager.getConnection(url,uid,pwd);
            smt=con.createStatement();
            String sql="select*from crecord";
            //smt.executeUpdate(sql);

            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
            {

               jComboBox1.addItem(rs.getString("c_id"));
               
         }
         }
         catch(Exception e)
         {

         }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel1.setText("Customer id");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer name", "Room type", "Room no.", "No. of days", "Extra facilities", "Room charges", "Price", "Discount", "GST", "Net amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jButton1)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //PreparedStatement p;

        // TODO add your handling code here:
      //  try{
   //   DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
        

         //   String uid="root";
           // String psw="";
         //   String url="jdbc:mysql://localhost:3306/project";
           // con=DriverManager.getConnection(url,uid,psw);
         //   smt=con.createStatement();
          // String sql="select * from crecord where c_id="+jComboBox1.getSelectedItem()+";";
          //  rs=smt.executeQuery(sql);
          //  while(rs.next()){
            //    String a,b,c,d,e,f,g,h,i,j;


               //   a=rs.getString("customer name");
              //  b=rs.getString("roomtype");
               // c=rs.getString("room_no");
               // d=rs.getString("no_day");
              //  e=rs.getString("ext_fac");
              //  f=rs.getString("room_chrg");
                //g=rs.getString("t_roomchrg");
                //h=rs.getString("dis");
                //i=rs.getString("gst");
                //j=rs.getString("net_amt");
               
                //m.addRow(new Object[]{a,b,c,d,e,f,g,h,i,j});
            //}
            //smt.close();
            //con.close();
        //}
           // catch(Exception e)
            //{
             //   JOptionPane.showMessageDialog(null, e.getMessage());
            //}

        try{
          DefaultTableModel m=( DefaultTableModel)jTable1.getModel();
            m.setRowCount(0);
            Class.forName("java.sql.DriverManager");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
            Statement s= con.createStatement();
            String sql="select * from crecord where c_id="+jComboBox1.getSelectedItem()+";";
            rs=s.executeQuery(sql);
          pst=con.prepareStatement(sql);
            while(rs.next()){
                String ss1=rs.getString("c_id");
                 String s1=rs.getString("c_name");
                String s2=rs.getString("roomtype");
                String s3=rs.getString("room_no");
                String s4=rs.getString("no_day");
                String s5=rs.getString("ext_fac");
                String s6=rs.getString("room_chrg");
                String s7=rs.getString("t_roomchrg");
                 String s8=rs.getString("dis");
                  String s9=rs.getString("gst");
                 
                     String s10=rs.getString("net_amt");

                      
//idate.setText(s1);
//cuname.setText(ss1);


                m.addRow(new Object[]{s1,s2,s3,s4,s5,s6,s7,s8,s9,s10});
            }
            rs.close();
            s.close();
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",1);
        }
































    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
